name: Pull Request - Build production

on:
  push:
    branches:
      - "*"
      - "*/*" # match all feature/ and fix/ branches
      - "!master" # exclude master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workingDirectory: ./wv8-finance-front-end

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      # Remove custom npmrc
      - run: rm .npmrc
        working-directory: ${{env.workingDirectory}}
      # - run: npm config set '//pkgs.dev.azure.com/woutervanacht/_packaging/Wv8-NuGet-Feed/npm/registry/:_authToken' ${{secrets.AZURE_DEVOPS_PAT}}
      - run: echo "${{secrets.AZURE_AUTH}}" > ~/.npmrc
      - run: npm config set @wv8:registry https://pkgs.dev.azure.com/woutervanacht/_packaging/Wv8-NuGet-Feed/npm/registry/
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ${{env.workingDirectory}}
      # `npm rebuild` will run all those post-install scripts for us.
      - run: npm rebuild && npm run prepare --if-present
        working-directory: ${{env.workingDirectory}}
      # for some reason npm install does not properly install angular cli.
      - run: npm install @angular/cli --global
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ${{env.workingDirectory}}
      # build angular production configuration
      - run: npm run "build:prod"
        working-directory: ${{env.workingDirectory}}
