name: Deploy Stef

on: workflow_dispatch

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    env:
      workingDirectory: ./wv8-finance-front-end
      distDirectory: ./wv8-finance-front-end/dist/*
      environmentFileDirectory: ./wv8-finance-front-end/src/environments/

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      - run: mv environment.prod.stef.ts environment.prod.ts
        working-directory: ${{env.environmentFileDirectory}}
      - run: sed -i 's@{secrets.BACKEND_URL}@${{secrets.BACKEND_URL_STEF}}@g' environment.prod.ts
        working-directory: ${{env.environmentFileDirectory}}
      - run: echo "${{secrets.AZURE_AUTH}}" > ~/.npmrc
      - run: npm config set @wv8:registry https://pkgs.dev.azure.com/woutervanacht/_packaging/Wv8-NuGet-Feed/npm/registry/
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ${{env.workingDirectory}}
      # `npm rebuild` will run all those post-install scripts for us.
      - run: npm rebuild && npm run prepare --if-present
        working-directory: ${{env.workingDirectory}}
      # for some reason npm install does not properly install angular cli.
      - run: npm install @angular/cli --global
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ${{env.workingDirectory}}
      # build angular production configuration
      - run: npm run "build:prod"
        working-directory: ${{env.workingDirectory}}
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USER }}
          server: ${{ secrets.FTP_HOST }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ${{env.distDirectory}}
          remote_path: ${{ secrets.FTP_FOLDER_STEF }}
          sftp_only: false
          delete_remote_files: true
